apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nexus-dev

resources:
- ../../base

replicas:
- count: 1
  name: nexus-api

images:
- name: ghcr.io/felipefranca07/nexus-api
  newName: ghcr.io/felipefranca07/nexus-api
  newTag: sha-6f8613d

patches:
- patch: |-
    - op: replace
      path: /data/APP_VERSION
      value: dev
  target:
    kind: ConfigMap
    name: nexus-api-config
