apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nexus-api-staging
  namespace: argocd
spec:
  project: nexus
  source:
    repoURL: "https://github.com/FelipeFranca07/Nexus-GitOps.git"
    targetRevision: main
    path: apps/nexus-api/overlays/staging
  destination:
    server: "https://kubernetes.default.svc"
    namespace: nexus-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
