apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nexus-staging

resources:
  - ../../base

replicas:
  - name: nexus-api
    count: 2

images:
  - name: ghcr.io/felipefranca07/nexus-api
    newTag: latest

patches:
  - target:
      kind: ConfigMap
      name: nexus-api-config
    patch: |-
      - op: replace
        path: /data/APP_VERSION
        value: staging
